# Generated by Django 2.1.2 on 2019-02-28 04:59

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=10)),
                ('customer_name', models.CharField(max_length=20)),
                ('customer_phone', models.IntegerField(default=0)),
                ('customer_email', models.EmailField(default='', max_length=50)),
                ('customer_address', models.TextField()),
                ('customer_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='Male', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('quant', models.CharField(max_length=10)),
                ('unit_price', models.CharField(max_length=10)),
                ('total', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptData',
            fields=[
                ('invoice_no', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('date', models.CharField(max_length=10)),
                ('amount', models.CharField(max_length=1)),
                ('mode', models.CharField(choices=[('card', 'Cash'), ('cheque', 'Cheque')], default='Cheque', max_length=6)),
                ('card_no', models.IntegerField(default=0)),
                ('cheque_no', models.IntegerField(default=0)),
                ('bank_name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=50)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(blank=True, null=True, upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(default='', max_length=50, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='invoice_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.ReceiptData'),
        ),
    ]
