# Generated by Django 2.0 on 2019-03-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptdata',
            name='email',
        ),
        migrations.AlterField(
            model_name='receiptdata',
            name='mode',
            field=models.CharField(choices=[('Card', 'cash'), ('Cheque', 'cheque')], default='Cheque', max_length=6),
        ),
    ]
