# Generated by Django 2.0 on 2019-03-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0003_auto_20190302_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptdata',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
