# Generated by Django 2.1 on 2019-03-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0005_uploads_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploads',
            name='status',
        ),
        migrations.AddField(
            model_name='receiptdata',
            name='mailed_status',
            field=models.BooleanField(default=False),
        ),
    ]
