# Generated by Django 2.0 on 2019-03-02 12:52

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ('Finance', '0007_auto_20190302_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='company',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='company',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='receiptdata',
            old_name='company',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='uploads',
            old_name='company',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='company',
            new_name='company_name',
        ),
    ]
