# Generated by Django 2.0 on 2019-03-02 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0008_auto_20190302_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company_name',
        ),
    ]
