# Generated by Django 2.1 on 2019-03-02 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0011_auto_20190302_1841'),
        ('Finance', '0006_auto_20190302_1738'),
    ]

    operations = [
    ]
