# Generated by Django 2.1.7 on 2019-03-02 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0012_merge_20190302_1850'),
        ('Finance', '0005_receiptdata_mailed_status'),
    ]

    operations = [
    ]
