# Generated by Django 2.0 on 2019-03-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0014_auto_20190303_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptdata',
            name='mode',
            field=models.CharField(choices=[('Card', 'card'), ('Cheque', 'cheque')], default='Cheque', max_length=6),
        ),
    ]
