# Generated by Django 2.1 on 2019-03-03 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0015_auto_20190303_0723'),
        ('Finance', '0014_auto_20190303_0839'),
    ]

    operations = [
    ]
