# Generated by Django 2.1 on 2019-03-03 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0016_merge_20190303_0850'),
        ('Finance', '0015_auto_20190303_0922'),
    ]

    operations = [
    ]
