# Generated by Django 2.1 on 2019-03-03 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0015_auto_20190303_0910'),
        ('Finance', '0016_auto_20190303_0938'),
    ]

    operations = [
    ]
