# Generated by Django 2.1 on 2019-03-03 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0016_auto_20190303_0938'),
        ('Finance', '0017_merge_20190303_0936'),
    ]

    operations = [
    ]
