# Generated by Django 2.1 on 2019-03-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0017_merge_20190303_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(blank=True, default='', max_length=50)),
                ('invoice_no', models.IntegerField(default=0, unique=True)),
                ('timestamp', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
