# Generated by Django 2.1 on 2019-03-03 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0019_logs_status'),
        ('Finance', '0018_merge_20190303_1424'),
    ]

    operations = [
    ]
